//Floyd²âÊÔÎÄ¼ş 
#include<stdio.h>
#include<stdlib.h>
#include<limits.h>
#include"GRAPHMATRIX.h" 
#include"FLOYD.h"
main(){
	Graph *g;
	VexType v1,v2;
	ShPath p[VEXSIZE][VEXSIZE];
	InitGraph(g);
	g->vexnum=4;
	g->vex[0].id=0;
	g->vex[0].used=1;
	g->vex[1].id=1;
	g->vex[1].used=1;
	g->vex[2].id=2;
	g->vex[2].used=1;
	g->vex[3].id=3;
	g->vex[3].used=1;
	g->arcnum=8;
	g->arc[0][1].data=1;
	g->arc[0][1].used=1;
	g->arc[0][3].data=4;
	g->arc[0][3].used=1;
	g->arc[1][2].data=2;
	g->arc[1][2].used=1;
	g->arc[1][3].data=2;
	g->arc[1][3].used=1;
	g->arc[2][0].data=3;
	g->arc[2][0].used=1;
	g->arc[2][1].data=5;
	g->arc[2][1].used=1;
	g->arc[2][3].data=8;
	g->arc[2][3].used=1;
	g->arc[3][2].data=6;
	g->arc[3][2].used=1;
	v1=g->vex[0];
	v2=g->vex[3];
	Floyd(g,p);
	TraverseFloyd(g,v1,v2,p);
	DestroyGraph(g);
}
